---

- name: install KVM
  yum:
    name:
      - qemu-kvm
      - libvirt
      - virt-install
      - bridge-utils
      - libselinux-python
    state: present
    become: yes
    delegate_to: "{{kvm_install_host}}"

- name: enable libvirt
  systemd: name=libvirt enabled=yes state=started
  become: yes
  delegate_to: "{{kvm_install_host}}"

- name: check if libvirt is loaded
  shell: "lsmod | grep kvm | wc -l"
  become: yes
  delegate_to: "{{kvm_install_host}}"
  register: libvirted_mod_exist

-fail:
  msg: "libvirt fail"
when: libvirt_mod_exist.stdout == '0'